# -*- coding: utf-8 -*-
"""firstAssign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TEJbz76_n1OVFeMcNBxkGyY10jayMWgX

**Q1**
"""

integer_var = 10
float_var = 10.5
string_var = "Hello, World!"
boolean_var = True


print(type(integer_var))
print(type(float_var))
print(type(string_var))
print(type(boolean_var))

addition = integer_var + float_var
subtraction = integer_var - float_var
multiplication = integer_var * float_var
division = integer_var / float_var

print("Addition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)

"""**Q2**"""

x = int(input("Enter a number: "))


if x % 2 == 0:
    print(f"The number {x} is even.")
else:
    print(f"The number {x} is odd.")

"""**Q3**"""

sentence = "Test sentence for Q3"

# Converting to uppercase and lowercase
uppercase_sentence = sentence.upper()
lowercase_sentence = sentence.lower()

# Splitting the sentence into a list of words
words_list = sentence.split()

# Finding the length of the sentence
sentence_length = len(sentence)

# Replacing a specific word
new_sentence = sentence.replace("fox", "cat")

print("Uppercase:", uppercase_sentence)
print("Lowercase:", lowercase_sentence)
print("Words list:", words_list)
print("Length of the sentence:", sentence_length)
print("Replaced sentence:", new_sentence)

"""**Q4**"""

numbers = [1, 2, 3, 4, 5]
for number in numbers:
    print(number * 2)


sum_of_numbers = 0
i = 1
while i <= 10:
    sum_of_numbers += i
    i += 1

print("Sum of numbers from 1 to 10:", sum_of_numbers)

"""**Q5**"""

fruits = ["apple", "banana", "cherry", "mango"]


lengths_of_fruits = [len(fruit) for fruit in fruits]


fruits.append("date")

# Sorting the list alphabetically
fruits.sort()

print("Lengths of fruits:", lengths_of_fruits)
print("Updated and sorted fruits list:", fruits)

"""**Q6**"""

book = {
    "title": "To Kill a Mockingbird",
    "author": "Harper Lee",
    "year": 1960
}


print("Title:", book["title"])
print("Author:", book["author"])
print("Year:", book["year"])


book["genre"] = "Fiction"


for key, value in book.items():
    print(f"{key}: {value}")